# Generated by Django 4.2.16 on 2024-10-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('positionName', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deflag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('deflag', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profile_service.user')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profile_service.user')),
                ('startDate', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateOfBirth', models.DateField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('socialSecurityNumber', models.CharField(max_length=20, null=True)),
                ('positionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_service.position')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('residentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profile_service.user')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidateId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('applicationDate', models.DateField()),
                ('resumeAttachment', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('positionId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_service.position')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('scheduleId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('trainingName', models.CharField(max_length=100)),
                ('trainingDate', models.DateField()),
                ('deflag', models.IntegerField(default=1)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_service.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TimeKeeping',
            fields=[
                ('recordId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('checkIn', models.DateTimeField()),
                ('checkOut', models.DateTimeField()),
                ('deflag', models.IntegerField(default=1)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_service.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('reviewId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('performanceReview', models.TextField()),
                ('discipline', models.TextField()),
                ('rewards', models.TextField()),
                ('deflag', models.IntegerField(default=1)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_service.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('leaveId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('leaveStartDate', models.DateField()),
                ('leaveEndDate', models.DateField()),
                ('leaveType', models.CharField(max_length=50)),
                ('deflag', models.IntegerField(default=1)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_service.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('contractId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('contractNumber', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefits', models.TextField()),
                ('terminationClauses', models.TextField()),
                ('attachments', models.CharField(max_length=255)),
                ('deflag', models.IntegerField(default=1)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_service.employee')),
            ],
        ),
    ]
